#+TITLE: How to locally install python
#+AUTHOR: phdenzel

  On a server or shared machine, you might want to install stuff locally, i.e. in your home directory.
  I often get asked how I installed python this way.
  This is what I did (more or less):

*** Installing in ~/local/python
    First, we need to create the directories, where python has to be installed.
    #+BEGIN_SRC shell
      mkdir -p ~/local/python
    #+END_SRC
    
    Then go to the created directories and download the python source code
    (I used 2.7.something, however if you're starting out completely new, I recommend 3.6.2).
    #+BEGIN_SRC shell
      cd ~/local/python
      wget https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tgz
    #+END_SRC
    
    Unpack it... do you remember the tar flags?
    #+BEGIN_SRC shell
      tar zxfv Python-2.7.13.tgz
    #+END_SRC

    Make the directories safe from outside influence
    #+BEGIN_SRC shell
      find ~/local/python -type d | xargs chmod 0755
    #+END_SRC
    
    ... and finally install in your local directory with
    #+BEGIN_SRC shell
      cd Python-2.7.13
      ./configure --prefix=$HOME/local/python
      make && make install
    #+END_SRC
    Make sure to include the ~--prefix~ flag, since this is where the output of ~make~ is installed.
    On UNIX machines this is by default in ~/usr/local~.
    
    If you've received an error message about the C compiler, you might have to change the second line to
    #+BEGIN_SRC shell
      CC=gcc ./configure --prefix=$HOME/local/python
    #+END_SRC
    or a similar compiler of your choice (that works).
    

*** Defining path variables

    Now that we have locally installed python, we have to define the path to the local library in our ~.bash_profile~.
    #+BEGIN_SRC shell
      export PATH=$HOME/local/python/Python-2.7.13/:$PATH
      export PYTHONPATH=$HOME/local/python/Python-2.7.13
    #+END_SRC
    
    To test if it worked type
    #+BEGIN_SRC shell
      source ~/.bash_profile
      which python
    #+END_SRC
    or something similar (like ~.bashrc~).
    If the output of ~which~ includes ~/local/python/~ it worked!

*** Setting up pip

    I use pip to install all my python libraries.

    Since python is already installed, it is relatively painless to install ~pip~.
    #+BEGIN_SRC shell :export
    wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py -O - | python - --user
    #+END_SRC
    
    This downloads and installs ~pip~ locally in ~$HOME/.local/bin~.
    Now, we just have to update the PATH in your ~.bash_profile~ and you're good to go...
    #+BEGIN_SRC shell
      export PATH=$PATH:$HOME/.local/bin
    #+END_SRC
    
    Again, test it with
    #+BEGIN_SRC shell
      source ~/.bash_profile
      which pip
    #+END_SRC
